#||

newtongeteulerangle
newtonseteulerangle

newtondeserializecallback
newtononbodydeserializationcallback
newtononbodyserializationcallback
newtononjointdeserializationcallback
newtononjointserializationcallback
newtononusercollisionserializationcallback
newtonserializecallback

||#
