;; newtonskeletoncontainerattachbone
;; newtonskeletoncontainerattachjointarray
;; newtonskeletoncontainercreate
;; newtonskeletoncontainerdelete
;; newtonskeletoncontainerfinalize
;; newtonskeletoncontainerfirstchild
;; newtonskeletoncontainergetbodyfromnode
;; newtonskeletoncontainergetparent
;; newtonskeletoncontainergetparentjointfromnode
;; newtonskeletoncontainergetroot
;; newtonskeletoncontainernextsibling
;; newtonskeletontdestructor
