(in-package :issac)

;; Split up the newton stuff

;;
;; CREATE FUNCS (sort em)


newtoncreateheightfieldcollision
newtoncreatescenecollision

newtoncreateusermeshcollision

newtoncreateex
;;
;; GETS 'n' SETS (sort em)

newtongeteulerangle
newtonseteulerangle


newtongetmemoryused
newtongetnumberofsubsteps
newtongetstacksize

newtonsetmemorysystem
newtonsetnumberofsubsteps
newtonsetperformanceclock


newtonsetstacksize
newtonsettransform




;;
;; CONTACT
newtoncontactgetcollision0
newtoncontactgetcollision1
newtoncontactgetcollisionid0
newtoncontactgetcollisionid1
newtoncontactgetmaterial
newtoncontactjointgetclosestdistance
newtoncontactjointgetcontactcount
newtoncontactjointgetfirstcontact
newtoncontactjointgetnextcontact
newtoncontactjointremovecontact
newtoncontactsprocess

;;
;; CONSTRAINT
newtonconstraintcreateball
newtonconstraintcreatecorkscrew
newtonconstraintcreatehinge
newtonconstraintcreateslider
newtonconstraintcreateuniversal
newtonconstraintcreateupvector
newtonconstraintcreateuserjoint
newtonconstraintdestructor



newton-deformable-body
newton-dynamic-body
newton-kinematic-body
newton-major-version
newton-minor-version
newtonalloc
newtonallocmemory
newtonapplyforceandtorque

newtonballgetjointforce
newtonballgetjointomega
newtonballsetconelimits


newtonboxparam
newtoncalculatespringdamperacceleration
newtoncapsuleparam
newtonchamfercylinderparam
newtonclothpatchmaterial

newtonconeparam

newtonconvexcollisioncalculatebuoyancyacceleration
newtonconvexcollisioncalculateinertialmatrix
newtonconvexcollisioncalculatevolume
newtonconvexhullgetfaceindices
newtonconvexhullgetvertexdata
newtonconvexhullparam

newtoncorkscrewcalculatestopaccel
newtoncorkscrewcalculatestopalpha
newtoncorkscrewgetjointforce
newtoncorkscrewgetjointomega
newtoncorkscrewgetjointposit
newtoncorkscrewgetjointveloc


newtoncylinderparam

newtondeformablemeshbeginconfiguration
newtondeformablemeshconstraintparticle
newtondeformablemeshcreateclusters
newtondeformablemeshendconfiguration
newtondeformablemeshgetfirstsegment
newtondeformablemeshgetnextsegment
newtondeformablemeshgetparticlecount
newtondeformablemeshgetparticleposition
newtondeformablemeshgetvertexcount
newtondeformablemeshgetvertexstreams
newtondeformablemeshparam
newtondeformablemeshsegment
newtondeformablemeshsegmentgetindexcount
newtondeformablemeshsegmentgetindexlist
newtondeformablemeshsegmentgetmaterialid
newtondeformablemeshunconstraintparticle
newtondeformablemeshupdaterendernormals


newtondestroybody
newtondestroycollision
newtondestroyjoint




newtonfree
newtonfreememory



newtonheightfieldcollisionparam
newtonhingecalculatestopalpha
newtonhingegetjointforce
newtonhingegetjointomega



newtonjobtask

newtonjoint
newtonjointgetbody0
newtonjointgetbody1
newtonjointgetcollisionstate
newtonjointgetinfo
newtonjointgetstiffness
newtonjointgetuserdata
newtonjointisactive
newtonjointiterator
newtonjointrecord
newtonjointsetcollisionstate
newtonjointsetdestructor
newtonjointsetstiffness
newtonjointsetuserdata

newtonmaterial
newtonmaterialcontactrotatetangentdirections
newtonmaterialcreategroupid
newtonmaterialdestroyallgroupid
newtonmaterialgetbodycollidingshape
newtonmaterialgetcontactfaceattribute
newtonmaterialgetcontactforce
newtonmaterialgetcontactmaxnormalimpact
newtonmaterialgetcontactmaxtangentimpact
newtonmaterialgetcontactnormalspeed
newtonmaterialgetcontactpenetration
newtonmaterialgetcontactpositionandnormal
newtonmaterialgetcontacttangentdirections
newtonmaterialgetcontacttangentspeed
newtonmaterialgetdefaultgroupid
newtonmaterialgetmaterialpairuserdata
newtonmaterialgetuserdata
newtonmaterialsetcallbackuserdata
newtonmaterialsetcontactelasticity
newtonmaterialsetcontactfrictioncoef
newtonmaterialsetcontactfrictionstate
newtonmaterialsetcontactnormaldirection
newtonmaterialsetcontactposition
newtonmaterialsetcontactsoftness
newtonmaterialsetcontacttangentacceleration
newtonmaterialsetcontacttangentfriction
newtonmaterialsetdefaultcollidable
newtonmaterialsetdefaultelasticity
newtonmaterialsetdefaultfriction
newtonmaterialsetdefaultsoftness
newtonmaterialsetsurfacethickness

newtononaabboverlap



newtononcontactgeneration
newtonscenecollisionaddsubcollision
newtonscenecollisionbeginaddremove
newtonscenecollisionendaddremove
newtonscenecollisiongetcollisionfromnode
newtonscenecollisiongetfirstnode
newtonscenecollisiongetnextnode
newtonscenecollisiongetnodebyindex
newtonscenecollisiongetnodeindex
newtonscenecollisionparam
newtonscenecollisionremovesubcollision
newtonscenecollisionremovesubcollisionbyindex
newtonscenecollisionsetsubcollisionmatrix



newtonskeletonbonejacobian
newtonskeletonbonejacobianpair
newtonskeletoncontainer
newtonskeletoncontainerattachbone
newtonskeletoncontainerattachjointarray
newtonskeletoncontainercreate
newtonskeletoncontainerdelete
newtonskeletoncontainerfinalize
newtonskeletoncontainerfirstchild
newtonskeletoncontainergetbodyfromnode
newtonskeletoncontainergetparent
newtonskeletoncontainergetparentjointfromnode
newtonskeletoncontainergetroot
newtonskeletoncontainernextsibling
newtonskeletontdestructor

newtonslidercalculatestopaccel
newtonslidergetjointposit
newtonslidergetjointveloc
newtonsphereparam




newtonuniversalcalculatestopalpha0
newtonuniversalcalculatestopalpha1
newtonuniversalgetjointangle1
newtonuniversalgetjointforce
newtonuniversalgetjointomega0
newtonuniversalgetjointomega1


newtonupvectorgetpin
newtonupvectorsetpin


newtonusercalculaterowzeroaccelaration

newtonusercontactpoint

newtonuserjoinrowscount

newtonuserjointaddangularrow
newtonuserjointaddgeneralrow
newtonuserjointaddlinearrow
newtonuserjointgetgeneralrow
newtonuserjointgetrowforce
newtonuserjointsetrowmaximumfriction
newtonuserjointsetrowminimumfriction
newtonuserjointsetrowspringdamperacceleration
newtonuserjointsetrowstiffness

newtonusermeshcollisionaabbtest
newtonusermeshcollisioncontinuousoverlaptest
newtonusermeshcollisiongetfacesinaabb
