newtoncompoundcollisionbeginaddremove
newtoncompoundcollisionendaddremove

newtondeformablemeshbeginconfiguration
newtondeformablemeshendconfiguration

newtonscenecollisionbeginaddremove
newtonscenecollisionendaddremove

newtontreecollisionbeginbuild
newtontreecollisionendbuild
