(in-package :issac)

;;
;; CONTACT
newtoncontactgetcollision0
newtoncontactgetcollision1
newtoncontactgetcollisionid0
newtoncontactgetcollisionid1
newtoncontactgetmaterial
newtoncontactjointgetclosestdistance
newtoncontactjointgetcontactcount
newtoncontactjointgetfirstcontact
newtoncontactjointgetnextcontact
newtoncontactjointremovecontact



;; maths
newtongeteulerangle
newtonseteulerangle
newtoncalculatespringdamperacceleration
